tbr_en_sentences = [
  "Once upon a time, in a faraway land, there lived a Prince.",
  "His name was Zigfried, and he was very unhappy.",
  "His father, the King, had died, and since then, everyone in the palace had forgotten how to smile.",
  "Without his father, Zigfried thought he would never feel happy again.",
  "Every day, Zigfried sat at the window in his room in the palace, looking at the birds in the trees.",
  "How can they sing and fly so free?",
  "They must not feel like me.",
  "His servant, Ozlowe, tried to make the prince smile by telling him jokes or doing funny tricks for him.",
  "But the Prince would not smile.",
  "I know you love me Ozlowe, but I cannot smile.",
  "My heart is broken.",
  "Ozlowe would not give up.",
  "Let's go for a walk, good Prince. ",
  "Maybe we can find something outside which will make you happy.",
  "If you wish Ozlowe, but I don't think there's anything that can make me happy.",
  "Ozlowe put on his hunting cap, and he took his crossbow.",
  "He enjoyed hunting and he hoped to catch a bird or a rabbit for the Prince.",
  "They walked through the forest until they came to a lake.",
  "On the lake there was a beautiful white swan.",
  "It had a gold crown on its head, that only Princesses wear.",
  "The swan swam towards the prince and looked into his eyes.",
  "The swan's eyes were so sad that Prince Zigfried felt sorry for it.",
  "Here is a creature which feels worse than I do.",
  "But why do you have that crown on your head?",
  "The swan opened its wings and cried out.",
  "I think it's trying to tell me something.", 
  "Ozlowe had his crossbow in his hands.",
  "He wanted to shoot the swan.",
  "I'll get that swan for you. Prince",
  "Just one minute.", 
  "Ozlowe, no!",
  "Before Ozlowe could shoot, a magic owl flew from a tree and took Ozlowe's cap off his head.",
  "This cast a spell on him, and he was turned to stone.",
  "The Prince did not understand.",
  "Ozlowe, what has happened to you? Speak to me!",
  "He looked back at the lake.",
  "The swan was gone.",
  "Everything I do goes wrong.",
  "This must have happened because of me!",
  "The Prince returned to the palace sadder than before, thinking to himself: 'If only Ozlowe were here! There is nothing good in my life any more'.", 
  "Zigfried's mother came to see him that night.",
  "She had something important to say.",
  "Zigfried, soon you will be eighteen years old.",
  "You must take your father's place as King.",
  "I am having a ball on your birthday so that you may choose a wife, and I will invite all the princesses from the other kingdoms." 
  "But I do not wish to marry, Mother.",
  "I do not love anyone.", 
  "You will learn to love someone.",
  "First, you must stop thinking of yourself.", 
  "If this will make you happy, I'll do it, Mother.",
  "It is not for my happiness that I am doing this.",
  "It is for yours, and all the other people in this land.",
  "You see, love is more powerful than we know.",
  "Without it, you will not be a great King.", 
  "His mother left him.",
  "He sat at the window, thinking of what she had said.",
  "He wanted to love someone with all his heart, but he didn't know who it would be.",
]


